# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
