# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_auto_20161119_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userrofile',
            new_name='UserProfile',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelapp.UserProfile'),
        ),
    ]
