# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelapp', '0005_auto_20161119_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', max_length=420)),
                ('time', models.DateTimeField(auto_now=True)),
                ('reviewed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewer_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelapp.UserProfile')),
            ],
        ),
    ]
