# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, default='not decided yet', max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_date',
            field=models.CharField(blank=True, default='not decided yet', max_length=20),
        ),
    ]
