# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_auto_20161129_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
