# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0011_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='img',
        ),
    ]
